### PR TITLE
Catalyst test should pass

### PR DESCRIPTION
**Pull request by chloechien**

### CODE REVIEW

**Comment by DilipSarkarVerily** [comment]
Thanks for your quick response, I will take a look at your changes in a while

**Comment by DilipSarkarVerily** [comment]
Thanks @chloechien , it works fine with your changes on your branch. I made exactly same changes on another branch, [PR#3](https://github.com/DilipSarkarVerily/monorepo-workspace/pull/3/files) and seem to get a different error. When I looked into the `package-lock.json`, I see some differences for the `Catalyst` packages in both the version. Actually, when I install the `catalyst` with `npm i`, I always get bellow error, only way for me to install the same is to add it in the `package.json` and run `npm i`. Is there any other way to install the same?

```
dilipsarkar@dilipsarkar:~/Verily/monorepo-workspace$ npm install https://github.com/verily-src/shared-angular-catalyst.git
npm ERR! Can't install git+https://github.com/verily-src/shared-angular-catalyst.git#77822eaea98e42e81de9b2ca837c1a87221fa0a3: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/dilipsarkar/.npm/_logs/2022-11-10T02_17_38_938Z-debug.log
```

Here is the error I'm getting with `ng test`, may be this will disappear if I copy `package-lock.json` content and run `npm ci` but wanted to check with you

```
dilipsarkar@dilipsarkar:~/Verily/monorepo-workspace$ ng test
✔ Browser application bundle generation complete.
10 11 2022 02:16:13.502:WARN [karma]: No captured browser, open http://localhost:9876/
10 11 2022 02:16:13.528:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
10 11 2022 02:16:13.528:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
10 11 2022 02:16:13.533:INFO [launcher]: Starting browser Chrome
10 11 2022 02:16:31.763:INFO [Chrome 107.0.0.0 (Linux x86_64)]: Connected on socket y4uTmOAdiDF6KGeeAAAB with id 45141213
Chrome 107.0.0.0 (Linux x86_64) ERROR: 'DEPRECATION: Access to 'this' in describe functions (and in arrow functions inside describe functions) is deprecated.
Error: 
    at <Jasmine>
    at Proxy.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/catalyst/dist/helpers.js:108:31)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.js:546:160)
    at Zone.run (http://localhost:9876/_karma_webpack_/polyfills.js:272:37)
    at Proxy.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/catalyst/node_modules/zone.js/fesm2015/zone-testing.js:549:29)
Note: This message will be shown only once. Set the verboseDeprecations config property to true to see every occurrence.'

```

**Comment by chloechien** [comment]
Hi @DilipSarkarVerily,

Please run cmd below to see if that works for you.

// check if your have a wrong version mapping in package-lock
rm -rf node_modules
rm package-lock.json

// update npm version
npm install -g npm
npm update

npm install

**Comment by DilipSarkarVerily** [comment]
> 

Hi @chloechien , I did try those commands yesterday couple of times but didn't help.

Do you have any comment on the bellow error?
```
dilipsarkar@dilipsarkar:~/Verily/monorepo-workspace$ npm install https://github.com/verily-src/shared-angular-catalyst.git
npm ERR! Can't install git+https://github.com/verily-src/shared-angular-catalyst.git#77822eaea98e42e81de9b2ca837c1a87221fa0a3: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/dilipsarkar/.npm/_logs/2022-11-10T02_17_38_938Z-debug.log
``

**Comment by chloechien** [comment]
I'm not sure why version is required by npm. I can't reproduce on my installed npm version. I suggest you could leave catalyst in package.json and to see if code works.

But if it is a must-have, you could try this:
1. Fork https://github.com/verily-src/shared-angular-catalyst
2. Add "version": "0.1.0" in package.json
3. try install your local catalyst instead of the verily-src catalyst

If this works good for you. We could add version in verily-src repo to adapt to this requirement.

**Comment by DilipSarkarVerily** [comment]
> I'm not sure why version is required by npm. I can't reproduce on my installed npm version. I suggest you could leave catalyst in package.json and to see if code works.
> 
> But if it is a must-have, you could try this:
> 
> 1. Fork https://github.com/verily-src/shared-angular-catalyst
> 2. Add "version": "0.1.0" in package.json
> 3. try install your local catalyst instead of the verily-src catalyst
> 
> If this works good for you. We could add version in verily-src repo to adapt to this requirement.

Thanks @chloechien , I tried in local, if we add the version that error seems to disappear. Could you please adopt the same in the main repo?

**Before adding version:**
```
dilipsarkar@dilipsarkar:~/Verily/Catalyst/monorepo-workspace$ npm i ../../shared-angular-catalyst
npm ERR! Can't install /usr/local/google/home/dilipsarkar/Verily/shared-angular-catalyst: Missing package version

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/dilipsarkar/.npm/_logs/2022-11-11T23_19_09_607Z-debug.log
```

**After adding version:**
```
dilipsarkar@dilipsarkar:~/Verily/Catalyst/monorepo-workspace$ npm i ../../shared-angular-catalyst
npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.

> @bazel/esbuild@5.7.1 postinstall /usr/local/google/home/dilipsarkar/Verily/shared-angular-catalyst/node_modules/@bazel/esbuild
> node npm_version_check.js


> @bazel/typescript@5.7.1 postinstall /usr/local/google/home/dilipsarkar/Verily/shared-angular-catalyst/node_modules/@bazel/typescript
> node npm_version_check.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (../../shared-angular-catalyst/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/material@13.3.3 requires a peer of @angular/cdk@13.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@2.0.0 requires a peer of jasmine-core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@2.0.0 requires a peer of karma-jasmine@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@13.3.3 requires a peer of @angular/cdk@13.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@13.3.3 requires a peer of @angular/forms@^13.0.0 || ^14.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@13.3.3 requires a peer of @angular/compiler@13.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/upgrade@13.3.3 requires a peer of @angular/compiler@13.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN @bazel/typescript@5.7.1 requires a peer of typescript@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
.
.
.

+ @angular/catalyst@0.0.1
added 173 packages from 809 contributors and audited 1091 packages in 34.622s

```

**Pull request merged**
